# Generated by Django 4.2.9 on 2024-01-24 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.task'),
        ),
    ]
